# Generated by Django 5.2.14 on 2026-05-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_backfill_attachment_knowledge_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="retrievallog",
            name="metadata_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
